# actions/goodbye-action/action.yml
name: 'My Goodbye Action'
description: 'A reusable GitHub Action that says goodbye.'
author: 'Your Name/Org'

inputs:
  who-to-say-goodbye:
    description: 'Who to say goodbye to'
    required: true
    default: 'World'

outputs:
  farewell-message:
    description: 'The farewell message'

runs:
  using: 'node20'
  main: 'dist/index.js' # Points to the compiled/packaged JS file within this action's directory

branding:
  icon: 'log-out'
  color: 'orange'
